/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/signUp'
import { Route as SignInImport } from './routes/signIn'
import { Route as AuthedImport } from './routes/_authed'
import { Route as AuthedUserImport } from './routes/_authed/_user'
import { Route as AuthedAdminImport } from './routes/_authed/_admin'
import { Route as AuthedUserIndexImport } from './routes/_authed/_user/index'
import { Route as AuthedUserSettingsImport } from './routes/_authed/_user/settings'
import { Route as AuthedUserPartnersImport } from './routes/_authed/_user/partners'
import { Route as AuthedUserObituaryImport } from './routes/_authed/_user/obituary'
import { Route as AuthedUserDashboardImport } from './routes/_authed/_user/dashboard'
import { Route as AuthedUserPartnersFuneralparlorsImport } from './routes/_authed/_user/partners_/funeral_parlors'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthedUserRoute = AuthedUserImport.update({
  id: '/_user',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAdminRoute = AuthedAdminImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedUserIndexRoute = AuthedUserIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedUserRoute,
} as any)

const AuthedUserSettingsRoute = AuthedUserSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedUserRoute,
} as any)

const AuthedUserPartnersRoute = AuthedUserPartnersImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthedUserRoute,
} as any)

const AuthedUserObituaryRoute = AuthedUserObituaryImport.update({
  id: '/obituary',
  path: '/obituary',
  getParentRoute: () => AuthedUserRoute,
} as any)

const AuthedUserDashboardRoute = AuthedUserDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedUserRoute,
} as any)

const AuthedUserPartnersFuneralparlorsRoute =
  AuthedUserPartnersFuneralparlorsImport.update({
    id: '/partners_/funeral_parlors',
    path: '/partners/funeral_parlors',
    getParentRoute: () => AuthedUserRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedAdminImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/_user': {
      id: '/_authed/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedUserImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/_user/dashboard': {
      id: '/_authed/_user/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedUserDashboardImport
      parentRoute: typeof AuthedUserImport
    }
    '/_authed/_user/obituary': {
      id: '/_authed/_user/obituary'
      path: '/obituary'
      fullPath: '/obituary'
      preLoaderRoute: typeof AuthedUserObituaryImport
      parentRoute: typeof AuthedUserImport
    }
    '/_authed/_user/partners': {
      id: '/_authed/_user/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthedUserPartnersImport
      parentRoute: typeof AuthedUserImport
    }
    '/_authed/_user/settings': {
      id: '/_authed/_user/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedUserSettingsImport
      parentRoute: typeof AuthedUserImport
    }
    '/_authed/_user/': {
      id: '/_authed/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedUserIndexImport
      parentRoute: typeof AuthedUserImport
    }
    '/_authed/_user/partners_/funeral_parlors': {
      id: '/_authed/_user/partners_/funeral_parlors'
      path: '/partners/funeral_parlors'
      fullPath: '/partners/funeral_parlors'
      preLoaderRoute: typeof AuthedUserPartnersFuneralparlorsImport
      parentRoute: typeof AuthedUserImport
    }
  }
}

// Create and export the route tree

interface AuthedUserRouteChildren {
  AuthedUserDashboardRoute: typeof AuthedUserDashboardRoute
  AuthedUserObituaryRoute: typeof AuthedUserObituaryRoute
  AuthedUserPartnersRoute: typeof AuthedUserPartnersRoute
  AuthedUserSettingsRoute: typeof AuthedUserSettingsRoute
  AuthedUserIndexRoute: typeof AuthedUserIndexRoute
  AuthedUserPartnersFuneralparlorsRoute: typeof AuthedUserPartnersFuneralparlorsRoute
}

const AuthedUserRouteChildren: AuthedUserRouteChildren = {
  AuthedUserDashboardRoute: AuthedUserDashboardRoute,
  AuthedUserObituaryRoute: AuthedUserObituaryRoute,
  AuthedUserPartnersRoute: AuthedUserPartnersRoute,
  AuthedUserSettingsRoute: AuthedUserSettingsRoute,
  AuthedUserIndexRoute: AuthedUserIndexRoute,
  AuthedUserPartnersFuneralparlorsRoute: AuthedUserPartnersFuneralparlorsRoute,
}

const AuthedUserRouteWithChildren = AuthedUserRoute._addFileChildren(
  AuthedUserRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedUserRoute: typeof AuthedUserRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedUserRoute: AuthedUserRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthedUserRouteWithChildren
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/dashboard': typeof AuthedUserDashboardRoute
  '/obituary': typeof AuthedUserObituaryRoute
  '/partners': typeof AuthedUserPartnersRoute
  '/settings': typeof AuthedUserSettingsRoute
  '/': typeof AuthedUserIndexRoute
  '/partners/funeral_parlors': typeof AuthedUserPartnersFuneralparlorsRoute
}

export interface FileRoutesByTo {
  '': typeof AuthedAdminRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/dashboard': typeof AuthedUserDashboardRoute
  '/obituary': typeof AuthedUserObituaryRoute
  '/partners': typeof AuthedUserPartnersRoute
  '/settings': typeof AuthedUserSettingsRoute
  '/': typeof AuthedUserIndexRoute
  '/partners/funeral_parlors': typeof AuthedUserPartnersFuneralparlorsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/_authed/_admin': typeof AuthedAdminRoute
  '/_authed/_user': typeof AuthedUserRouteWithChildren
  '/_authed/_user/dashboard': typeof AuthedUserDashboardRoute
  '/_authed/_user/obituary': typeof AuthedUserObituaryRoute
  '/_authed/_user/partners': typeof AuthedUserPartnersRoute
  '/_authed/_user/settings': typeof AuthedUserSettingsRoute
  '/_authed/_user/': typeof AuthedUserIndexRoute
  '/_authed/_user/partners_/funeral_parlors': typeof AuthedUserPartnersFuneralparlorsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/signIn'
    | '/signUp'
    | '/dashboard'
    | '/obituary'
    | '/partners'
    | '/settings'
    | '/'
    | '/partners/funeral_parlors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/signIn'
    | '/signUp'
    | '/dashboard'
    | '/obituary'
    | '/partners'
    | '/settings'
    | '/'
    | '/partners/funeral_parlors'
  id:
    | '__root__'
    | '/_authed'
    | '/signIn'
    | '/signUp'
    | '/_authed/_admin'
    | '/_authed/_user'
    | '/_authed/_user/dashboard'
    | '/_authed/_user/obituary'
    | '/_authed/_user/partners'
    | '/_authed/_user/settings'
    | '/_authed/_user/'
    | '/_authed/_user/partners_/funeral_parlors'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/signIn",
        "/signUp"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/_admin",
        "/_authed/_user"
      ]
    },
    "/signIn": {
      "filePath": "signIn.tsx"
    },
    "/signUp": {
      "filePath": "signUp.tsx"
    },
    "/_authed/_admin": {
      "filePath": "_authed/_admin.tsx",
      "parent": "/_authed"
    },
    "/_authed/_user": {
      "filePath": "_authed/_user.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/_user/dashboard",
        "/_authed/_user/obituary",
        "/_authed/_user/partners",
        "/_authed/_user/settings",
        "/_authed/_user/",
        "/_authed/_user/partners_/funeral_parlors"
      ]
    },
    "/_authed/_user/dashboard": {
      "filePath": "_authed/_user/dashboard.tsx",
      "parent": "/_authed/_user"
    },
    "/_authed/_user/obituary": {
      "filePath": "_authed/_user/obituary.tsx",
      "parent": "/_authed/_user"
    },
    "/_authed/_user/partners": {
      "filePath": "_authed/_user/partners.tsx",
      "parent": "/_authed/_user"
    },
    "/_authed/_user/settings": {
      "filePath": "_authed/_user/settings.tsx",
      "parent": "/_authed/_user"
    },
    "/_authed/_user/": {
      "filePath": "_authed/_user/index.tsx",
      "parent": "/_authed/_user"
    },
    "/_authed/_user/partners_/funeral_parlors": {
      "filePath": "_authed/_user/partners_/funeral_parlors.tsx",
      "parent": "/_authed/_user"
    }
  }
}
ROUTE_MANIFEST_END */
